### ISSUE TITLE
Optimize, stabilize file downloads

### ISSUE THREAD

**Issue by nbitzz** [mollersuite/monofile#44]
Maybe stream attachments & fetch messages from the API as the download goes on to allow it to start immediately?

**Comment by nbitzz** [comment]
> fetch messages from the API as the download goes on
Guess we should probably use the Workers API for this..? @Jack5079
Another alternative is just getting another message after we've sent the data from the last message, I don't think that the overhead from that would be significant + would probably be better anyway

**Comment by nbitzz** [comment]
readFileStream still needs a little cleanup but this issue is basically done so

**Comment by nbitzz** [comment]
@Jack5079 Are you like.going to handle fixing readFileStream or do i do it.Cause if you are i'll actually i'll just assign you now hold on

**Comment by Jack5079** [comment]
> @Jack5079 Are you like.going to handle fixing readFileStream or do i do it.Cause if you are i'll actually i'll just assign you now hold on

![image](https://github.com/mollersuite/monofile/assets/29169102/c536d580-0db2-4e03-a95a-727d4b19d46e)

**Comment by nbitzz** [comment]
Meow

**Comment by Jack5079** [comment]
![image](https://github.com/mollersuite/monofile/assets/29169102/e90837ad-72a4-4320-832a-e49eb321092c)

**Comment by nbitzz** [comment]
We should blow her up

**Comment by caffeinatedcharlie** [comment]
you're going to do WHAAAAAA

**Comment by nbitzz** [comment]
Oh wait this is basically done . Basically just  cleanup so i will close
