### ISSUE TITLE
Markofile

### ISSUE THREAD

**Issue by Jack5079** [mollersuite/monofile#45]
Svelte is [turning to shit](https://svelte.dev/blog/runes) so we will need to find a new framework.
I propose Marko.

## Advantages

- It is trivial to combine a Marko Run and Hono server: `npm run build src/server.ts`, and in there something like
```js
import * as Run from "@marko/run/router" // Run uses Request and Response
import { Hono } from "hono" // So does Hono
app.use("/", (c, next) => Run.fetch(c.req.raw) ?? next()) // i think? I had something before that worked I need to test more
```
- Marko lets you stream pages. This means, for example, we can send the CSS of a preview page before we have the metadata
- Marko's [Tags API](https://dev.to/ryansolid/introducing-the-marko-tags-api-preview-37o4) has reactivity like Svelte
- Marko 5 (current) won't hydrate components that don't have JS
- Marko 6 (future) is resumable - no hydration at all

## Disadvantages

- Data loading not clear when combining it with Hono (if we want to use idiomatic Marko **Run**) although we could simply do whatever we do in Svelte since we aren't using SvelteKit anyway
- Less Marko developers
- No transitions
- No scoped CSS (although we aren't using that anyway)

**Comment by nbitzz** [comment]
Thank god marko starts with an M every new improvement we make regarding frameworks must have a related pun on monofile or fyle

**Comment by nbitzz** [comment]
For Markofile, since we'll be using Marko Run (probably), let's take care of account management (and maybe the file list display) on separate routes
I think this should make #28 easier (or slightly less of a weird problem) to solve <img src=https://mahiro.oyama.pictures/m height=32>

**Comment by Jack5079** [comment]
Also @nbitzz I reccomend you read https://github.com/marko-js/run#path-structure

**Comment by Jack5079** [comment]
actually the whole readme

**Comment by nbitzz** [comment]
> actually the whole readme

was planning on it, dw

**Comment by Jack5079** [comment]
I'm rewriting monofile in SvelteKit instead, when Marko Run improves I will revisit it
