### ISSUE TITLE
Large Files fail to upload

### ISSUE THREAD

**Issue by CrazyDev05** [mollersuite/monofile#46]
when i try to upload a large file (in my case 500MiB)
i get the following error
```
HeadersTimeoutError: Headers Timeout Error
    at Timeout.onParserTimeout [as _onTimeout] (/var/www/monofile/node_modules/undici/lib/client.js:902:28)
    at listOnTimeout (node:internal/timers:575:11)
    at process.processTimers (node:internal/timers:514:7) {
  code: 'UND_ERR_HEADERS_TIMEOUT'
}
```

**Comment by nbitzz** [comment]
I don't believe I've seen this before, *maybe* raise your requestTimeout in config.json?

**Comment by CrazyDev05** [comment]
Good point...

**Comment by CrazyDev05** [comment]
how large should i make it?

**Comment by nbitzz** [comment]
Whatever you think would work. Also, what branch are you on? Are you on a non-master/stable branch? Are you cloning a file?

**Comment by CrazyDev05** [comment]
I'm on the main branch/i cloned the git

**Comment by CrazyDev05** [comment]
is the timeout in ms?

**Comment by nbitzz** [comment]
> is the timeout in ms?

Yeah. I'm not sure how Discord.js uploads the files, but I do believe I got a different error for timeouts... could be different now, though

If boosting requestTimeout doesn't fix it, maybe decrease your Discord file size? That fixed some issues on the main instances

The only place I know undici is used in is axios, so it could also be an issue with the file you're trying to clone

**Comment by CrazyDev05** [comment]
i already decreased `maxDiscordFileSize` to `10485760`

**Comment by CrazyDev05** [comment]
Wait I misunderstood the cloning file question, I'm trying to upload a file from my pc (the file just contains `Hello \n` to test the upload)

**Comment by nbitzz** [comment]
> Wait I misunderstood the cloning file question, I'm trying to upload a file from my pc (the file just contains `Hello \n` to test the upload)

That's... really weird. I'll check DJS's codebase when I have time. How fast is your internet?

**Comment by CrazyDev05** [comment]
The server has 1gbit/s, I have 30mbit/s up
and i still have the same error after changing the `requestTimeout` to `10800000` (failed after 3.5 min)

**Comment by nbitzz** [comment]
> The server has 1gbit/s (up/down), I have 30mbit/s up
> 
> and i still have the same error after changing the `requestTimeout` to `10800000` (failed after 3.5 min)

I'll be honest... I have zero idea  of what's happening.

`git stash`, `git checkout stable`, and `git stash apply` is the best advice I can give here, but I doubt that'd work; master and stable aren't that different...

**Comment by CrazyDev05** [comment]
Maybe some kind of discord limitation?

**Comment by nbitzz** [comment]
> Maybe some kind of discord limitation?

I know @Jack5079 got it to work with 10MiB chunks, and I'm not sure what's limiting you. What provider are you using for your server?

**Comment by CrazyDev05** [comment]
It should already be fixed https://github.com/discordjs/discord.js/pull/8679

**Comment by nbitzz** [comment]
[Hetzner was apparently banned from Discord's API once](https://github.com/discord/discord-api-docs/issues/744#issuecomment-438322565), but I'm not sure if this is still true, and the fact that you're getting a timeout over an actual proper error *is* strange. Try running locally or with another provider and see if that works, maybe...?

**Comment by CrazyDev05** [comment]
interestingly i can upload small files, but not large ones

**Comment by nbitzz** [comment]
> interestingly i can upload small files, but not large ones

Try uploading a file in the 10MiB range, then a file in the 100MiB+ range, and we'll see how that plays out...?

**Comment by CrazyDev05** [comment]
- [x] 10MB
- [x] 40MB
- [x] 90MB
- [x] 160MB
- [x] 250MB
- [x] 360MB
- [x] 490MB
now I'm confused

**Comment by CrazyDev05** [comment]
Trying 500MB again

**Comment by CrazyDev05** [comment]
now i get http error 504
```html
<html>
   <head>
      <title>504 Gateway Time-out</title>
   </head>
   <body>
      <center>
         <h1>504 Gateway Time-out</h1>
      </center>
      <hr>
      <center>nginx</center>
   </body>
</html>
<!-- a padding to disable MSIE and Chrome friendly error page --><!-- a padding to disable MSIE and Chrome friendly error page --><!-- a padding to disable MSIE and Chrome friendly error page --><!-- a padding to disable MSIE and Chrome friendly error page --><!-- a padding to disable MSIE and Chrome friendly error page --><!-- a padding to disable MSIE and Chrome friendly error page -->
```

**Comment by CrazyDev05** [comment]
i already changed the admin password and how long should i make the timeout?

**Comment by nbitzz** [comment]
> i already changed the admin password and how long should i make the timeout?

...Longer than it is currently?

**Comment by CrazyDev05** [comment]
Tried and 500 (HeadersTimeoutError) back...

**Comment by nbitzz** [comment]
> Tried 700MB and error 500 (HeadersTimeoutError) is back...

Hmm.... how much RAM do you have? What's the maximum file size on your instance? I know this probably won't help much, but I'd like to know more.
I have no idea what's causing this...

**Comment by CrazyDev05** [comment]
it seems to be a discord issue

**Comment by CrazyDev05** [comment]
Maybe progressively uploading instead of bulk uploading the files could help?

**Comment by nbitzz** [comment]
> Maybe progressively uploading instead of bulk uploading the files could help?

As in, one file per message, or streaming uploads to Discord?
Upload streaming is set for monofile 2.0 (#16).
If you'd like, we can add a maxFilesPerMessage parameter to config.json which would allow you to upload only one chunk at a time.

**Comment by CrazyDev05** [comment]
i meant like one file per message and maybe also upload streaming

**Comment by nbitzz** [comment]
Prooooooooobably fixed with upload streaming i'll close this now

**Comment by nbitzz** [comment]
I mean I managed a 10gb file on the api-v1 test instance and pfile is serving 250gb of data now so I think we're good
