### ISSUE TITLE
Switch to JWTs

### ISSUE THREAD

**Issue by nbitzz** [mollersuite/monofile#54]
We. don't use jwts. and we probably should

**Comment by nbitzz** [comment]
Should we consider this for the "like really fucking easy" label

**Comment by Jack5079** [comment]
What the fuck since when did we have that

**Comment by nbitzz** [comment]
> What the fuck since when did we have that

Since like 30 minutes ago

**Comment by nbitzz** [comment]
@Jack5079 is it even worth it to use JWTs?

We need to store the signing key... *somewhere*, and we still need to store all of the data in the JWT on the server if we want to do session management. 

The only benefit I can think of: not needing to make an extra request to some new endpoint to check your token's scopes. Worth it? Probably

**Comment by Jack5079** [comment]
Yeah I have no fucking idea

**Comment by nbitzz** [comment]
How much data do we even store in the JWT? We probably don't want to make it a Fat Fuck but I don't know

**Comment by nbitzz** [comment]
Solved in #70
