### ISSUE TITLE
[2.0.0-dev] monofile errors out when a 100mb+ file is uploaded behind cloudflare tunnels

### ISSUE THREAD

**Issue by choke-dev** [mollersuite/monofile#72]
services behind cloudflare tunnels have a 100mb upload limit, anything higher than that returns a 413 from cloudflare

![msedge_b55EpbFv6d](https://github.com/mollersuite/monofile/assets/47597850/f79152b1-e4b5-4a25-b96c-9fa3bb65bf05)

a potential solution to this could be a configurable option to enable/disable chunked uploads

**Comment by nbitzz** [comment]
chunking uploads between multiple requests, you mean?

**Comment by nbitzz** [comment]
if so, i'm not sure how i'd set it up and how to handle certain cases, i'll talk it out with jack ig. will be leaving unlabeled until i talk with him about this

**Comment by choke-dev** [comment]
i fixed the issue for myself by using a caddy reverse proxy, but i would still like to see the [potential fix](https://github.com/mollersuite/monofile/issues/72#issuecomment-2111651364) getting added

**Comment by nbitzz** [comment]
we've decided this is a job for the http proxy, not us; sorry
